{"category": "ham", "to_address": "Alberto Monteiro <albmont@centroin.com.br>", "from_address": "Duncan Murdoch <murdoch@stats.uwo.ca>", "subject": "Re: [R] Testing for existence inside a function", "body": "On 5/15/2007 3:06 PM, Alberto Monteiro wrote:\n> Talbot Katz wrote:\n>> \n>> I'm having trouble testing for existence of an object inside a function.\n>> \n> No, you are having trouble testing for existence of an object\n> _before_ the function is called :-)\n> \n>> Suppose I have a function:\n>> \n>> f<-function(x){\n>> ...\n>> }\n>> \n>> and I call it with argument y:\n>> \n>> f(y)\n>> \n>> I'd like to check inside the function whether argument y exists.\n>>\n> This can't be done, because the error happens before f is called.\n> \n> Try this:\n> \n> f <- function(x) x + 1\n> f(y.does.not.exist)\n> y.does.not.exist\n> \n> The error message is (almost) the same, and it happens when\n> parsing the line. There's no way to change f to change this.\n\nThat description is true in some languages, but not in R.  R doesn't \ncheck that args to functions are valid until it needs to use them.  For \nexample:\n\n > f <- function(y) 1  # doesn't care if y exists\n > f(y.does.not.exist)\n[1] 1\n\n______________________________________________\nR-help@stat.math.ethz.ch mailing list\nhttps://stat.ethz.ch/mailman/listinfo/r-help\nPLEASE do read the posting guide http://www.R-project.org/posting-guide.html\nand provide commented, minimal, self-contained, reproducible code.\n\n"}